### ISSUE TITLE
about multi-gpu support

### ISSUE THREAD

**Issue by pipipopo** [junyanz/BicycleGAN#34]
Hi, thanks for your amazing work. I have a problem with the multi-gpu support. The original batchsize is 2 for a real image and another random. In fact it's one pair. If we want to use multi-gpu for faster training, the batch size should be larger. But simply changing the batchsize causes error. May I know is it easy to modify the code for this purpose?

**Comment by junyanz** [comment]
What is your error? Have you set `--gpu_ids`?

**Comment by pipipopo** [comment]
create web directory ../checkpoints/edges2shoes/edges2shoes_bicycle_gan/web...
Traceback (most recent call last):
  File "./train.py", line 34, in <module>
    model.optimize_parameters()
  File "../BicycleGAN-master/models/bicycle_gan_model.py", line 211, in optimize_parameters
    self.update_G_and_E()
  File "../BicycleGAN-master/models/bicycle_gan_model.py", line 199, in update_G_and_E
    self.backward_EG()
  File "../BicycleGAN-master/models/bicycle_gan_model.py", line 151, in backward_EG
    self.loss_G_GAN = self.backward_G_GAN(self.fake_data_encoded, self.netD, self.opt.lambda_GAN)
  File "../BicycleGAN-master/models/bicycle_gan_model.py", line 143, in backward_G_GAN
    pred_fake = netD(fake)
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "../BicycleGAN-master/models/networks.py", line 263, in forward
    result.append(self.model[i](down))
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "../anaconda2/envs/xx/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)

**Comment by pipipopo** [comment]
After reading pytorch docs i still don't know how to set the data to devices in BicycleGAN....

**Comment by pipipopo** [comment]
Should 
net = torch.nn.DataParallel(net, gpu_ids) 
cooperate with any 
data.to(device)?

**Comment by junyanz** [comment]
I found the issue. If you set `--netD basic_256` and `--netD2 basic_256`, it should work. It seems that the multi-GPU issue comes from multi-scale D (`--netD basic_256_multi`). Ihaven't had time to address the issue there.  I also updated the code so that it is compatible with pix2pix/CycleGAN. You may want to check out the latest commit.
